
include("areachart_examples.jl")
include("distplot_examples.jl")
include("external_formats_example.jl")
include("kerneldensity_examples.jl")
include("linechart_examples.jl")
include("pages_examples.jl")
include("path_examples.jl")
include("picture_examples.jl")
include("piechart_examples.jl")
include("pivottable_examples.jl")
include("scatter3d_examples.jl")
include("scatterplot_examples.jl")
include("scattersurface3d_example.jl")
include("slides_examples.jl")
include("table_examples.jl")
include("textblock_examples.jl")

