using JSPlots, DataFrames, Dates, StableRNGs
rng = StableRNG(123)

println("Creating CodeBlock examples...")

# Prepare header
header = TextBlock("""
<h1>CodeBlock Examples</h1>
<p>This page demonstrates how to use CodeBlock elements in JSPlots to display Julia code with syntax highlighting and execute it to generate visualizations.</p>
<p>CodeBlocks are perfect for creating literate programming documents where you show both the code and its output.</p>
""")

# Example 1: CodeBlock from a function
# First, define a function that generates example data
function generate_sample_data()
    n = 50
    x = 1:n
    y1 = cumsum(randn(rng, n)) .+ 100
    y2 = cumsum(randn(rng, n)) .+ 100

    return DataFrame(
        day = x,
        stock_a = y1,
        stock_b = y2,
        category = repeat(["Tech", "Finance"], inner=25)
    )
end

# Create a CodeBlock from the function
example1_text = TextBlock("""
<h2>Example 1: CodeBlock from a Function</h2>
<p>Here we create a CodeBlock from a function that generates random stock data. The code is displayed with syntax highlighting, and we can execute it to get the data.</p>
""")

code1 = CodeBlock(generate_sample_data, notes="This function generates random walk stock price data")

# Execute the code to get the data
df1 = code1()

# Create a chart from the generated data
chart1 = LineChart(:stock_chart, df1, :df1;
    x_cols = [:day],
    y_cols = [:stock_a, :stock_b],
    title = "Stock Prices Over Time",
    notes = "Data generated by the code above"
)

# Example 2: CodeBlock with code that creates a chart
example2_text = TextBlock("""
<h2>Example 2: Showing Code and Chart Together</h2>
<p>This example shows how to display the code that creates a chart, alongside the chart itself.</p>
""")

# Define a function that creates a complete chart
function create_pie_chart()
    df = DataFrame(
        category = ["Product A", "Product B", "Product C", "Product D"],
        sales = [45000, 32000, 28000, 15000]
    )

    return PieChart(:sales_pie, df, :pie_data;
        color_cols = [:category],
        value_cols = [:sales],
        title = "Sales by Product"
    ), df
end

code2 = CodeBlock(create_pie_chart, notes="This function creates a pie chart showing sales by product")
chart2, df2 = code2()

# Example 3: Creating a CodeBlock from a code string
example3_text = TextBlock("""
<h2>Example 3: CodeBlock from a Code String</h2>
<p>Sometimes you want to show code for educational purposes without executing it. Here's an example:</p>
""")

tutorial_code = """
# Tutorial: Creating a Simple Scatter Plot
using JSPlots, DataFrames, StableRNGs
rng = StableRNG(42)

# Step 1: Create your data
df = DataFrame(
    x = rand(rng, 100),
    y = rand(rng, 100),
    size = rand(rng, 100) .* 50,
    color = rand(rng, ["red", "blue", "green"], 100)
)

# Step 2: Create the scatter plot
scatter = ScatterPlot(:my_scatter, df, :my_data;
    x_cols = [:x],
    y_cols = [:y],
    size_col = :size,
    color_cols = [:color],
    title = "My First Scatter Plot"
)

# Step 3: Export to HTML
create_html(scatter, "output.html")
"""

code3 = CodeBlock(tutorial_code, Val(:code),
    notes="This code is for display only - not executed in this example")

# Example 4: Multiple related code blocks showing a workflow
example4_text = TextBlock("""
<h2>Example 4: Multi-Step Workflow</h2>
<p>This example demonstrates how to show multiple code blocks that build on each other, creating a complete data analysis workflow.</p>
""")

# Step 1: Data preparation
function prepare_analysis_data()
    dates = Date(2024,1,1):Day(1):Date(2024,1,31)
    df = DataFrame(
        date = dates,
        temperature = 15 .+ 10 .* sin.(2π .* (1:31) ./ 31) .+ randn(rng, 31) .* 2,
        humidity = 60 .+ 15 .* cos.(2π .* (1:31) ./ 31) .+ randn(rng, 31) .* 5,
        city = repeat(["New York", "Boston"], inner=16)[1:31]
    )
    return df
end

step1_text = TextBlock("<h3>Step 1: Prepare the Data</h3>")
step1_code = CodeBlock(prepare_analysis_data,
    notes="Generate synthetic weather data for analysis")
weather_df = step1_code()

# Step 2: Create visualization
step2_text = TextBlock("<h3>Step 2: Visualize the Data</h3>")

create_weather_chart_code = """
# Create a line chart showing temperature trends
weather_chart = LineChart(:weather, weather_df, :weather_data;
    x_cols = [:date],
    y_cols = [:temperature, :humidity],
    title = "January Weather Patterns",
    notes = "Temperature (°C) and Humidity (%)"
)
"""

step2_code = CodeBlock(create_weather_chart_code, Val(:code),
    notes="Code to create the weather visualization")

# Actually create the chart (since the code block is display-only, we create it separately)
weather_chart = LineChart(:weather, weather_df, :weather_data;
    x_cols = [:date],
    y_cols = [:temperature, :humidity],
    title = "January Weather Patterns"
)

# Example 5: Best Practices summary
best_practices = TextBlock("""
<h2>Best Practices for Using CodeBlock</h2>
<div style="background-color: #f0f7ff; padding: 20px; border-left: 4px solid #0066cc; margin: 20px 0;">
    <h3>When to Use CodeBlock</h3>
    <ul>
        <li><strong>Documentation:</strong> Show how to use your analysis code</li>
        <li><strong>Reproducibility:</strong> Display the exact code that generated results</li>
        <li><strong>Teaching:</strong> Create tutorials with code examples</li>
        <li><strong>Reports:</strong> Include methodology alongside visualizations</li>
    </ul>

    <h3>CodeBlock Creation Methods</h3>
    <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
        <thead>
            <tr style="background-color: #e6f2ff;">
                <th style="padding: 10px; text-align: left; border: 1px solid #ccc;">Method</th>
                <th style="padding: 10px; text-align: left; border: 1px solid #ccc;">Syntax</th>
                <th style="padding: 10px; text-align: left; border: 1px solid #ccc;">Executable?</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="padding: 10px; border: 1px solid #ccc;">From Function</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><code>CodeBlock(my_function)</code></td>
                <td style="padding: 10px; border: 1px solid #ccc;">✓ Yes</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ccc;">From File</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><code>CodeBlock("script.jl")</code></td>
                <td style="padding: 10px; border: 1px solid #ccc;">✓ Yes</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ccc;">From String</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><code>CodeBlock(code_str, Val(:code))</code></td>
                <td style="padding: 10px; border: 1px solid #ccc;">✗ No</td>
            </tr>
        </tbody>
    </table>

    <h3>Executing Code</h3>
    <p>For executable CodeBlocks, call them like functions using <code>codeblock()</code>:</p>
    <pre style="background-color: #f5f5f5; padding: 10px; border-radius: 5px;">
# Single return value
data = code_block()

# Multiple return values
chart, data = code_block()

# Alternative (but cb() is preferred)
data = execute_codeblock(code_block)
    </pre>

    <h3>Tips</h3>
    <ul>
        <li>Use the <code>notes</code> parameter to provide context about what the code does</li>
        <li>Combine CodeBlocks with charts to show both process and result</li>
        <li>For source extraction from functions, consider installing <code>CodeTracking.jl</code> for better results</li>
        <li>Use display-only CodeBlocks for tutorials or examples that shouldn't be executed</li>
    </ul>
</div>
""")

# Summary
summary = TextBlock("""
<h2>Summary</h2>
<p>This page demonstrated CodeBlock features:</p>
<ul>
    <li><strong>Function-based CodeBlocks:</strong> Extract and display function source code</li>
    <li><strong>Executable code:</strong> Run code and use the results in visualizations</li>
    <li><strong>Display-only blocks:</strong> Show tutorial or example code</li>
    <li><strong>Multi-step workflows:</strong> Document complete analysis processes</li>
    <li><strong>Integration with charts:</strong> Show code alongside its output</li>
</ul>
<p><strong>CodeBlocks make your analyses reproducible and educational by showing the code that generated every visualization!</strong></p>
""")

# Combine all datasets into a dictionary
datasets = Dict{Symbol,DataFrame}(
    :df1 => df1,
    :pie_data => df2,
    :weather_data => weather_df
)

# Create a single page combining all examples
page = JSPlotPage(
    datasets,
    [
        header,
        example1_text, code1, chart1,
        example2_text, code2, chart2,
        example3_text, code3,
        example4_text, step1_text, step1_code, step2_text, step2_code, weather_chart,
        best_practices,
        summary
    ],
    tab_title = "CodeBlock Examples"
)

create_html(page, "generated_html_examples/codeblock_examples.html")

println("\n" * "="^60)
println("CodeBlock examples created successfully!")
println("="^60)
println("\nFile created: generated_html_examples/codeblock_examples.html")
println("\nThis page includes:")
println("  • CodeBlock from a function (executable)")
println("  • CodeBlock showing chart creation code and the resulting chart")
println("  • CodeBlock from a code string (display-only)")
println("  • Multi-step workflow with multiple code blocks")
println("  • Best practices and usage guide")
println("  • Syntax highlighting for all code blocks")
println("\nTip: Execute code blocks with codeblock() syntax to get results!")
